import React, { useState } from 'react';
import {
  TrendingUp,
  Award,
  BookOpen,
  Anchor,
  Megaphone,
  Smile,
  Hash,
  Sparkles,
  CheckCircle,
  Copy,
  Check,
  RefreshCw,
  Zap,
  ArrowRight,
  Clock,
  Download,
  Share2,
  BarChart3,
  Calendar
} from 'lucide-react';

export default function AnalysisDashboard({ data, onApplyVariation, onAddHashtag }) {
  const [activeTab, setActiveTab] = useState(0);
  const [copiedIndex, setCopiedIndex] = useState(null);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  if (!data) return null;

  const {
    engagementScore = 0,
    readability = {},
    hook = {},
    cta = {},
    sentiment = {},
    hashtags = {},
    postingSchedule = {},
    suggestions = [],
    variations = [],
    metrics = {}
  } = data;

  const getScoreBadge = (score) => {
    if (score >= 80) return { label: 'High Potential', color: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40' };
    if (score >= 60) return { label: 'Moderate Reach', color: 'bg-amber-500/20 text-amber-300 border-amber-500/40' };
    return { label: 'Needs Optimization', color: 'bg-red-500/20 text-red-300 border-red-500/40' };
  };

  const badge = getScoreBadge(engagementScore);

  const handleCopyVariation = (text, index) => {
    navigator.clipboard.writeText(text);
    setCopiedIndex(index);
    setTimeout(() => setCopiedIndex(null), 2000);
  };

  const handleDownloadReport = () => {
    const reportContent = `# Social Media Content Audit Report
Generated by Social Media Content Analyzer
Date: ${new Date().toLocaleString()}

========================================
1. ENGAGEMENT SCORE: ${engagementScore}/100 (${badge.label})
========================================
- Readability Score: ${readability.score}/100 (${readability.label})
- Hook Quality Score: ${hook.score}% (${hook.feedback})
- Call To Action Score: ${cta.score}% (${cta.hasCTA ? 'Present' : 'Missing'})
- Detected Tone: ${sentiment.tone}
- Detected Sentiment: ${sentiment.sentiment}

========================================
2. METRICS BREAKDOWN
========================================
- Character Count: ${metrics.characterCount}
- Word Count: ${metrics.wordCount}
- Estimated Reading Time: ${metrics.readingTimeMinutes} min
- Emoji Count: ${metrics.emojiCount}
- Hashtag Count: ${hashtags.existingCount}

========================================
3. BEST POSTING SCHEDULE & AUDIENCE
========================================
- Best Platform: ${postingSchedule.bestPlatform || 'LinkedIn'}
- Ideal Audience: ${postingSchedule.audienceType || 'Broad Audience'}
- Recommended Times:
${(postingSchedule.recommendedTimes || []).map(t => `  • ${t}`).join('\n')}

========================================
4. ACTIONABLE RECOMMENDATIONS
========================================
${suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}

========================================
5. AI-OPTIMIZED VARIATIONS
========================================
${variations.map((v, i) => `[Style: ${v.title}]\n${v.text}\n--------------------`).join('\n\n')}
`;

    const blob = new Blob([reportContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `social_content_audit_${Date.now()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 2500);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner: Engagement Score & Core Breakdown */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-indigo-500/5 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col lg:flex-row items-center justify-between gap-6">
          {/* Main Score Radial / Gauge */}
          <div className="flex items-center gap-6">
            <div className="relative flex items-center justify-center">
              <svg className="w-32 h-32 transform -rotate-90">
                <circle
                  cx="64"
                  cy="64"
                  r="52"
                  className="stroke-slate-800"
                  strokeWidth="10"
                  fill="transparent"
                />
                <circle
                  cx="64"
                  cy="64"
                  r="52"
                  className={`${
                    engagementScore >= 80
                      ? 'stroke-emerald-400'
                      : engagementScore >= 60
                      ? 'stroke-amber-400'
                      : 'stroke-red-400'
                  } transition-all duration-1000 ease-out`}
                  strokeWidth="10"
                  strokeDasharray={326}
                  strokeDashoffset={326 - (326 * engagementScore) / 100}
                  strokeLinecap="round"
                  fill="transparent"
                />
              </svg>
              <div className="absolute flex flex-col items-center justify-center text-center">
                <span className="text-3xl font-black text-white font-mono">{engagementScore}</span>
                <span className="text-[10px] uppercase tracking-wider text-slate-400 font-semibold">Score</span>
              </div>
            </div>

            <div>
              <div className="flex items-center gap-2 mb-1">
                <h2 className="text-xl font-bold text-slate-100">Engagement Score</h2>
                <span className={`text-xs px-2.5 py-0.5 rounded-full border font-medium ${badge.color}`}>
                  {badge.label}
                </span>
              </div>
              <p className="text-xs text-slate-400 max-w-md">
                Calculated based on opening hook, call-to-action strength, readability index, emoji density, and structural formatting.
              </p>

              {/* Quick stats inline */}
              <div className="flex flex-wrap items-center gap-3 mt-3 text-xs text-slate-300">
                <span className="bg-slate-950 px-2.5 py-1 rounded-md border border-slate-800">
                  Tone: <strong className="text-purple-300">{sentiment.tone}</strong>
                </span>
                <span className="bg-slate-950 px-2.5 py-1 rounded-md border border-slate-800">
                  Readability: <strong className="text-indigo-300">{readability.label} ({readability.score}/100)</strong>
                </span>
              </div>
            </div>
          </div>

          {/* Export & Actions */}
          <div className="flex flex-col sm:flex-row items-center gap-3 w-full lg:w-auto">
            <button
              onClick={handleDownloadReport}
              className="w-full sm:w-auto px-4 py-2.5 bg-slate-800 hover:bg-slate-700 border border-slate-700 text-slate-200 text-xs font-semibold rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg"
            >
              {downloadSuccess ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  <span className="text-emerald-300">Report Downloaded!</span>
                </>
              ) : (
                <>
                  <Download className="w-4 h-4 text-indigo-400" />
                  <span>Download Audit Report (.md)</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* 4 Core Metrics Mini-Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mt-6 pt-6 border-t border-slate-800/80">
          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex flex-col justify-between">
            <span className="text-[11px] text-slate-400 flex items-center gap-1">
              <Anchor className="w-3.5 h-3.5 text-indigo-400" /> Hook Quality
            </span>
            <div className="mt-2 flex items-baseline justify-between">
              <span className="text-lg font-bold text-white font-mono">{hook.score}%</span>
              <span className="text-[10px] text-slate-400">
                {hook.score >= 80 ? 'Strong' : 'Moderate'}
              </span>
            </div>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex flex-col justify-between">
            <span className="text-[11px] text-slate-400 flex items-center gap-1">
              <Megaphone className="w-3.5 h-3.5 text-purple-400" /> Call to Action
            </span>
            <div className="mt-2 flex items-baseline justify-between">
              <span className="text-lg font-bold text-white font-mono">{cta.score}%</span>
              <span className="text-[10px] text-slate-400">
                {cta.hasCTA ? 'Present' : 'Missing'}
              </span>
            </div>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex flex-col justify-between">
            <span className="text-[11px] text-slate-400 flex items-center gap-1">
              <Smile className="w-3.5 h-3.5 text-pink-400" /> Emojis
            </span>
            <div className="mt-2 flex items-baseline justify-between">
              <span className="text-lg font-bold text-white font-mono">{metrics.emojiCount}</span>
              <span className="text-[10px] text-slate-400">
                {metrics.emojiCount >= 1 && metrics.emojiCount <= 6 ? 'Balanced' : 'Check'}
              </span>
            </div>
          </div>

          <div className="bg-slate-950 p-3 rounded-xl border border-slate-800 flex flex-col justify-between">
            <span className="text-[11px] text-slate-400 flex items-center gap-1">
              <Hash className="w-3.5 h-3.5 text-emerald-400" /> Hashtags
            </span>
            <div className="mt-2 flex items-baseline justify-between">
              <span className="text-lg font-bold text-white font-mono">{hashtags.existingCount}</span>
              <span className="text-[10px] text-slate-400">
                {hashtags.existingCount > 0 ? 'Optimal' : 'None'}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Row 2: Best Posting Schedule & Emotion Spectrum */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Best Posting Schedule & Platform Fit */}
        <div className="lg:col-span-2 bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col justify-between">
          <div>
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-md font-semibold text-slate-100 flex items-center gap-2">
                <Calendar className="w-5 h-5 text-indigo-400" />
                Target Audience & Best Posting Window
              </h3>
              <span className="text-xs px-2.5 py-0.5 rounded-full bg-indigo-950 border border-indigo-800/60 text-indigo-300 font-medium">
                Best Fit: {postingSchedule.bestPlatform || 'LinkedIn'}
              </span>
            </div>

            <p className="text-xs text-slate-400 mb-4">
              <strong>Recommended Audience:</strong> {postingSchedule.audienceType || 'Industry professionals & tech creators'}
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
              {(postingSchedule.recommendedTimes || [
                'Tuesday 9:00 AM - 11:00 AM',
                'Thursday 1:00 PM - 3:00 PM'
              ]).map((timeSlot, idx) => (
                <div
                  key={idx}
                  className="p-3 bg-slate-950 border border-slate-800 rounded-xl flex items-center gap-3 text-xs text-slate-200"
                >
                  <Clock className="w-4 h-4 text-amber-400 flex-shrink-0" />
                  <span>{timeSlot}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Platform Match Score Bars */}
          {postingSchedule.platformSuitability && (
            <div className="pt-4 border-t border-slate-800 space-y-2 text-xs">
              <div className="flex items-center justify-between text-slate-400">
                <span>Platform Match Distribution:</span>
              </div>
              <div className="grid grid-cols-3 gap-2 text-[11px]">
                <div className="bg-slate-950 p-2 rounded-lg border border-slate-800">
                  <div className="flex justify-between text-sky-400 mb-1">
                    <span>X (Twitter)</span>
                    <span className="font-mono">{postingSchedule.platformSuitability.twitter}%</span>
                  </div>
                  <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden">
                    <div className="bg-sky-500 h-full" style={{ width: `${postingSchedule.platformSuitability.twitter}%` }} />
                  </div>
                </div>

                <div className="bg-slate-950 p-2 rounded-lg border border-slate-800">
                  <div className="flex justify-between text-blue-400 mb-1">
                    <span>LinkedIn</span>
                    <span className="font-mono">{postingSchedule.platformSuitability.linkedin}%</span>
                  </div>
                  <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden">
                    <div className="bg-blue-500 h-full" style={{ width: `${postingSchedule.platformSuitability.linkedin}%` }} />
                  </div>
                </div>

                <div className="bg-slate-950 p-2 rounded-lg border border-slate-800">
                  <div className="flex justify-between text-pink-400 mb-1">
                    <span>Instagram</span>
                    <span className="font-mono">{postingSchedule.platformSuitability.instagram}%</span>
                  </div>
                  <div className="w-full bg-slate-800 rounded-full h-1.5 overflow-hidden">
                    <div className="bg-pink-500 h-full" style={{ width: `${postingSchedule.platformSuitability.instagram}%` }} />
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Emotion Spectrum */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col justify-between">
          <div>
            <h3 className="text-md font-semibold text-slate-100 flex items-center gap-2 mb-3">
              <BarChart3 className="w-5 h-5 text-purple-400" />
              Emotional Resonance
            </h3>
            <p className="text-xs text-slate-400 mb-4">
              NLP intensity score of key emotional triggers in the text.
            </p>

            <div className="space-y-3">
              {(sentiment.emotions || [
                { name: 'Curiosity', value: 85 },
                { name: 'Confidence', value: 90 },
                { name: 'Urgency', value: 40 },
                { name: 'Engagement', value: 88 }
              ]).map((emo, idx) => (
                <div key={idx} className="space-y-1">
                  <div className="flex justify-between text-xs text-slate-300">
                    <span>{emo.name}</span>
                    <span className="font-mono text-purple-300 font-semibold">{emo.value}%</span>
                  </div>
                  <div className="w-full bg-slate-950 rounded-full h-2 overflow-hidden border border-slate-800">
                    <div
                      className="bg-gradient-to-r from-indigo-500 to-purple-500 h-full rounded-full transition-all duration-700"
                      style={{ width: `${emo.value}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="mt-4 pt-3 border-t border-slate-800 text-[11px] text-slate-400 flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-purple-400" />
            <span>Tone: <strong className="text-slate-200">{sentiment.tone}</strong></span>
          </div>
        </div>
      </div>

      {/* Row 3: Actionable Suggestions & AI Variations */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Actionable Recommendations & Hashtag Generator */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col">
          <h3 className="text-md font-semibold text-slate-100 flex items-center gap-2 mb-4">
            <Zap className="w-5 h-5 text-amber-400" />
            Actionable Optimization Checklist
          </h3>

          <div className="space-y-3 flex-1">
            {suggestions.map((item, idx) => (
              <div
                key={idx}
                className="p-3 bg-slate-950/70 border border-slate-800/80 rounded-xl flex items-start gap-3 text-xs text-slate-300"
              >
                <div className="p-1 bg-amber-500/10 rounded text-amber-400 mt-0.5">
                  <ArrowRight className="w-3.5 h-3.5" />
                </div>
                <span className="leading-relaxed">{item}</span>
              </div>
            ))}
          </div>

          {/* Hashtags Optimizer */}
          <div className="mt-6 pt-4 border-t border-slate-800">
            <h4 className="text-xs font-semibold text-slate-300 flex items-center gap-1.5 mb-2">
              <Hash className="w-3.5 h-3.5 text-emerald-400" />
              Recommended High-Reach Hashtags (1-Click Insert)
            </h4>
            <div className="flex flex-wrap gap-2">
              {hashtags.recommended && hashtags.recommended.length > 0 ? (
                hashtags.recommended.map((item, idx) => {
                  const tagText = typeof item === 'object' ? item.tag : item;
                  const reachLabel = typeof item === 'object' ? item.reach : 'High';
                  return (
                    <button
                      key={idx}
                      onClick={() => onAddHashtag && onAddHashtag(tagText)}
                      className="text-xs px-2.5 py-1 bg-emerald-950/40 hover:bg-emerald-900/60 border border-emerald-800/60 text-emerald-300 rounded-lg transition-colors flex items-center gap-1.5 group"
                      title="Click to insert into post"
                    >
                      <span>{tagText}</span>
                      <span className="text-[9px] px-1 rounded bg-emerald-900/80 text-emerald-400 font-mono">
                        {reachLabel}
                      </span>
                      <span className="text-[10px] text-emerald-500 group-hover:text-white">+</span>
                    </button>
                  );
                })
              ) : (
                <span className="text-xs text-slate-400">Hashtags already optimal!</span>
              )}
            </div>
          </div>
        </div>

        {/* AI Re-written Variations */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl flex flex-col">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-md font-semibold text-slate-100 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-400" />
              AI-Optimized Variations
            </h3>
            <span className="text-[11px] text-slate-400">1-click apply</span>
          </div>

          {/* Variation Tabs */}
          <div className="flex gap-2 border-b border-slate-800 pb-2 mb-4 overflow-x-auto">
            {variations.map((varItem, idx) => (
              <button
                key={idx}
                onClick={() => setActiveTab(idx)}
                className={`text-xs px-3 py-1.5 rounded-lg transition-all font-medium whitespace-nowrap ${
                  activeTab === idx
                    ? 'bg-indigo-600 text-white shadow'
                    : 'bg-slate-950 text-slate-400 hover:text-slate-200 border border-slate-800'
                }`}
              >
                {varItem.title}
              </button>
            ))}
          </div>

          {/* Selected Variation Display */}
          {variations[activeTab] && (
            <div className="flex-1 flex flex-col justify-between">
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-xs text-slate-200 whitespace-pre-wrap font-sans leading-relaxed max-h-56 overflow-y-auto">
                {variations[activeTab].text}
              </div>

              <div className="mt-4 flex items-center justify-between gap-3">
                <button
                  onClick={() => handleCopyVariation(variations[activeTab].text, activeTab)}
                  className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs flex items-center gap-1.5 transition-colors"
                >
                  {copiedIndex === activeTab ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-emerald-400" /> Copied!
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" /> Copy Text
                    </>
                  )}
                </button>

                <button
                  onClick={() => onApplyVariation && onApplyVariation(variations[activeTab].text)}
                  className="px-4 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white font-medium rounded-lg text-xs flex items-center gap-1.5 shadow transition-all"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                  <span>Apply to Editor</span>
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
